### ISSUE TITLE
epoch_size not an optional parameter

### ISSUE THREAD

**Issue by aaronfderybel** [BNN-UPC/ignnition#117]
The documentation for the epoch_size training parameter says that leaving it blank, it will consider the entire dataset as one epoch.
https://ignnition.org/doc/train_and_evaluate.html#epoch-size

However leaving this blank produces following error:

>ValueError: When providing an infinite dataset, you must specify the number of steps to run (if you did not intend to create an infinite dataset, make sure to not call `repeat()` on the dataset)

This seems to be a data generator related issue, see tf docs: https://www.tensorflow.org/api_docs/python/tf/data/Dataset#repeat
Looking at the source code it seems that the datagenerator repeat is hardcoded to True: https://github.com/BNN-UPC/ignnition/blob/905e4aa756ad6dd92d620f5f8b37d8190bb5273a/ignnition/ignnition_model.py#L761

Right now leaving the epoch_size blank does not give the desired behaviour of training

**Comment by MiquelFerriol** [comment]
Dear @AaronDeRybelHowest ,
Thank you very much for pointing out this issue.

As you already said, the data generator repeat argument is hardcoded to true. This causes the generator to be "infinite" and, consequently, Tensorflow raises the aforementioned error.

This problem has been fixed in #119 at the nightly branch and will be in the main release in a few days.

Thank you very much for your time in investigating and reporting the issue.

Best regards,
Miquel
